version: '3.9'
services:
  app:
    env_file:
      - .dockerenv
    build: .
    ports:
      - "3002:3002"
      - "3004:3004"
    entrypoint: ["sh", "./entrypoint.sh"]
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:holabola00@db:5432/mydb
      REDIS_URL: redis://redis:6379
      command: sh -c "npx prisma migrate deploy && pnpm start"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: holabola00
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  redis:
    image: redis:7
    ports:
      - "6378:6379"

volumes:
  db_data:
